-- use this file to map the AP item ids to your items
-- first value is the code of the target item and the second is the item type (currently only "toggle", "progressive" and "consumable" but feel free to expand for your needs!)
-- here are the SM items as an example: https://github.com/Cyb3RGER/sm_ap_tracker/blob/main/scripts/autotracking/item_mapping.lua

ScriptHost:LoadScript("scripts/autotracking/Spel2ItemCodes.lua")

ITEM_MAPPING = {

-- Permanent Upgrades
    [Spel2AP.permanent_upgrades.Health] = {"hp", "consumable"},
    [Spel2AP.permanent_upgrades.Bomb] = {"bombs", "consumable"},
    [Spel2AP.permanent_upgrades.Rope] = {"ropes", "consumable"},
    [Spel2AP.permanent_upgrades.Cosmic_Ocean_Checkpoint] = {"COCheckpoint", "consumable"},
    [Spel2AP.world_unlocks.Progressive_World] = {"secondworld", "progressive"},

-- Restricted Items (Locked Items)
    [Spel2AP.locked_items.Alien_Compass] = {"RAlienCompass", "toggle"},
    [Spel2AP.locked_items.Ankh] = {"Rankh", "toggle"},
    [Spel2AP.locked_items.Arrow_of_Light] = {"RArrowOfLight", "toggle"},
    [Spel2AP.locked_items.Camera] = {"Rcamera", "toggle"},
    [Spel2AP.locked_items.Cape] = {"Rcape", "toggle"},
    [Spel2AP.locked_items.Climbing_Gloves] = {"RClimbingGloves", "toggle"},
    [Spel2AP.locked_items.Clone_Gun] = {"RCloneGun", "toggle"},
    [Spel2AP.locked_items.Compass] = {"Rcompass", "toggle"},
    [Spel2AP.locked_items.Crown] = {"Rcrown", "toggle"},
    [Spel2AP.locked_items.Eggplant] = {"Reggplant", "toggle"},
    [Spel2AP.locked_items.Eggplant_Crown] = {"REggplantCrown", "toggle"},
    [Spel2AP.locked_items.Elixir] = {"Relixir", "toggle"},
    [Spel2AP.locked_items.Excalibur] = {"RExcalibur", "toggle"},
    [Spel2AP.locked_items.Four_Leaf_Clover] = {"RFourLeafClover", "toggle"},
    [Spel2AP.locked_items.Freeze_Ray] = {"RFreezeRay", "toggle"},
    [Spel2AP.locked_items.Hedjet] = {"Rhedjet", "toggle"},
    [Spel2AP.locked_items.Hou_Yis_Bow] = {"RHouYisBow", "toggle"},
    [Spel2AP.locked_items.Hoverpack] = {"Rhoverpack", "toggle"},
    [Spel2AP.locked_items.Jetpack] = {"Rjetpack", "toggle"},
    [Spel2AP.locked_items.Kapala] = {"Rkapala", "toggle"},
    [Spel2AP.locked_items.Machete] = {"Rmachete", "toggle"},
    [Spel2AP.locked_items.Mattock] = {"Rmattock", "toggle"},
    [Spel2AP.locked_items.Paste] = {"Rpaste", "toggle"},
    [Spel2AP.locked_items.Pitchers_Mitt] = {"RPitchersMitt", "toggle"},
    [Spel2AP.locked_items.Plasma_Cannon] = {"RPlasmaCannon", "toggle"},
    [Spel2AP.locked_items.Powerpack] = {"Rpowerpack", "toggle"},
    [Spel2AP.locked_items.Scepter] = {"Rscepter", "toggle"},
    [Spel2AP.locked_items.Shield] = {"RMetalShield", "toggle"},
    [Spel2AP.locked_items.Skeleton_Key] = {"RSkeletonKey", "toggle"},
    [Spel2AP.locked_items.Spectacles] = {"Rspectacles", "toggle"},
    [Spel2AP.locked_items.Spike_Shoes] = {"RSpikeShoes", "toggle"},
    [Spel2AP.locked_items.Spring_Shoes] = {"RSpringShoes", "toggle"},
    [Spel2AP.locked_items.Tablet_of_Destiny] = {"RTabletOfDestiny", "toggle"},
    [Spel2AP.locked_items.Telepack] = {"Rtelepack", "toggle"},
    [Spel2AP.locked_items.Teleporter] = {"Rteleporter", "toggle"},
    [Spel2AP.locked_items.True_Crown] = {"RTrueCrown", "toggle"},
    [Spel2AP.locked_items.Udjat_Eye] = {"Rudjat", "toggle"},
    [Spel2AP.locked_items.Ushabti] = {"Rushabti", "toggle"},
    [Spel2AP.locked_items.Vlads_Cape] = {"RVladsCape", "toggle"},
    [Spel2AP.locked_items.Webgun] = {"Rwebgun", "toggle"},

-- Starting Items (Upgrades)
    [Spel2AP.upgrades.Ankh] = {"SAnkh", "toggle"},
    [Spel2AP.upgrades.Arrow_of_Light] = {"SArrowOfLight", "toggle"},
    [Spel2AP.upgrades.Camera] = {"Scamera", "toggle"},
    [Spel2AP.upgrades.Cape] = {"Scape", "toggle"},
    [Spel2AP.upgrades.Climbing_Gloves] = {"SClimbingGloves", "toggle"},
    [Spel2AP.upgrades.Clone_Gun] = {"SCloneGun", "toggle"},
    [Spel2AP.upgrades.Compass] = {"Scompass", "toggle"},
    [Spel2AP.upgrades.Crown] = {"Scrown", "toggle"},
    [Spel2AP.upgrades.Eggplant] = {"Seggplant", "toggle"},
    [Spel2AP.upgrades.Eggplant_Crown] = {"SEggplantCrown", "toggle"},
    [Spel2AP.upgrades.Elixir] = {"Selixir", "toggle"},
    [Spel2AP.upgrades.Excalibur] = {"SExcalibur", "toggle"},
    [Spel2AP.upgrades.Four_Leaf_Clover] = {"Sclover", "toggle"},
    [Spel2AP.upgrades.Freeze_Ray] = {"SFreezeRay", "toggle"},
    [Spel2AP.upgrades.Hedjet] = {"Shedjet", "toggle"},
    [Spel2AP.upgrades.Hou_Yis_Bow] = {"SHouYisBow", "toggle"},
    [Spel2AP.upgrades.Hoverpack] = {"Shoverpack", "toggle"},
    [Spel2AP.upgrades.Jetpack] = {"Sjetpack", "toggle"},
    [Spel2AP.upgrades.Kapala] = {"Skapala", "toggle"},
    [Spel2AP.upgrades.Machete] = {"Smachete", "toggle"},
    [Spel2AP.upgrades.Mattock] = {"Smattock", "toggle"},
    [Spel2AP.upgrades.Paste] = {"Spaste", "toggle"},
    [Spel2AP.upgrades.Pitchers_Mitt] = {"SPitchersMitt", "toggle"},
    [Spel2AP.upgrades.Plasma_Cannon] = {"SPlasmaCannon", "toggle"},
    [Spel2AP.upgrades.Powerpack] = {"Spowerpack", "toggle"},
    [Spel2AP.upgrades.Scepter] = {"Sscepter", "toggle"},
    [Spel2AP.upgrades.Shield] = {"SMetalShield", "toggle"},
    [Spel2AP.upgrades.Skeleton_Key] = {"SSkeletonKey", "toggle"},
    [Spel2AP.upgrades.Spectacles] = {"Sspectacles", "toggle"},
    [Spel2AP.upgrades.Spike_Shoes] = {"SSpikeShoes", "toggle"},
    [Spel2AP.upgrades.Spring_Shoes] = {"SSpringShoes", "toggle"},
    [Spel2AP.upgrades.Tablet_of_Destiny] = {"STabletOfDestiny", "toggle"},
    [Spel2AP.upgrades.Telepack] = {"Stelepack", "toggle"},
    [Spel2AP.upgrades.Teleporter] = {"Steleporter", "toggle"},
    [Spel2AP.upgrades.True_Crown] = {"STrueCrown", "toggle"},
    [Spel2AP.upgrades.Udjat_Eye] = {"Sudjat", "toggle"},
    [Spel2AP.upgrades.Ushabti] = {"Sushabti", "toggle"},
    [Spel2AP.upgrades.Vlads_Cape] = {"SVladsCape", "toggle"},
    [Spel2AP.upgrades.Webgun] = {"Swebgun", "toggle"},

-- Character
    [Spel2AP.characters.Ana_Spelunky] = {"ana", "toggle"},
    [Spel2AP.characters.Margaret_Tunnel] = {"margaret", "toggle"},
    [Spel2AP.characters.Colin_Northward] = {"colin", "toggle"},
    [Spel2AP.characters.Roffy_D_Sloth] = {"roffy", "toggle"},
    [Spel2AP.characters.Alto_Singh] = {"alto", "toggle"},
    [Spel2AP.characters.Liz_Mutton] = {"liz", "toggle"},
    [Spel2AP.characters.Nekka_the_Eagle] = {"nekka", "toggle"},
    [Spel2AP.characters.LISE_Project] = {"lise", "toggle"},
    [Spel2AP.characters.Coco_Von_Diamonds] = {"coco", "toggle"},
    [Spel2AP.characters.Manfred_Tunnel] = {"manfred", "toggle"},
    [Spel2AP.characters.Little_Jay] = {"jay", "toggle"},
    [Spel2AP.characters.Tina_Flan] = {"tina", "toggle"},
    [Spel2AP.characters.Valerie_Crump] = {"valerie", "toggle"},
    [Spel2AP.characters.Au] = {"au", "toggle"},
    [Spel2AP.characters.Demi_Von_Diamonds] = {"demi", "toggle"},
    [Spel2AP.characters.Pilot] = {"pilot", "toggle"},
    [Spel2AP.characters.Princess_Airyn] = {"airyn", "toggle"},
    [Spel2AP.characters.Dirk_Yamaoka] = {"dirk", "toggle"},
    [Spel2AP.characters.Guy_Spelunky] = {"guy", "toggle"},
    [Spel2AP.characters.Classic_Guy] = {"classic", "toggle"}
}